app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('dashboard.urls')),
    path('empresa/', include('empresa.urls')),
    path('equipamento/', include('equipamento.urls')),
    path('colaborador/', include('colaborador.urls')),
    path('tipo_equipamento/', include('tipo_equipamento.urls')),
    path('usuario/', include('usuario.urls')),
    path('', include('usuario.urls')),
]

empresa/urls.py
from django.urls import path
from .views import empresa_views

urlpatterns = [
    path('cadastrar', empresa_views.cadastrar_empresas,
         name='cadastrar_empresa'),
    path('listar', empresa_views.listar_empresas,
         name='listar_empresas'),
    path('editar/<int:id>', empresa_views.editar_empresa,
         name='editar_empresa'),
    path('listar_empresa/<int:id>',
         empresa_views.listar_empresa_id, name='listar_empresa_id'),
    path('erro_empresa',
         empresa_views.erro_inativar, name='erro_empresa'),
]

empresa/models.py
from django.db import models


# Create your models here.
class Empresa(models.Model):
    nome = models.CharField(max_length=100, null=False, blank=False)
    cnpj = models.CharField(max_length=18, null=False,
                            blank=False, unique=True)
    status = models.BooleanField(default=True)

    class Meta:
        ordering = ['nome']

    def __str__(self):
        return self.nome

equipamento/models.py
from django.db import models

from empresa.models import Empresa
from colaborador.models import Colaborador
from tipo_equipamento.models import TipoEquipamento

# Create your models here.
SITUACAO_EQUIPAMENTO_CHOICES = (
    ('0', 'Novo'),
    ('1', 'Em operação'),
    ('2', 'Em manutenção'),
    ('3', 'Disponivel'),
    ('4', 'Indisponível'),
)

class Equipamento(models.Model):
    tag_patrimonio = models.CharField(
        max_length=30, null=False, blank=False, unique=True)
    tipo_equipamento = models.ForeignKey(
        TipoEquipamento, on_delete=models.PROTECT, limit_choices_to={'status': True})
    pedido = models.CharField(
        max_length=20, null=True, blank=True)
    data = models.DateField(
        blank=True, null=True)
    situacao = models.CharField(
        max_length=1, choices=SITUACAO_EQUIPAMENTO_CHOICES, null=False, blank=False)
    empresa = models.ForeignKey(
        Empresa, on_delete=models.PROTECT, limit_choices_to={'status': True})
    colaborador = models.ForeignKey(
        Colaborador, on_delete=models.PROTECT, limit_choices_to={'status': True})
    marca = models.CharField(
        max_length=50)
    modelo = models.CharField(
        max_length=50)
    especificacoes = models.CharField(
        max_length=100, null=True, blank=True)
    acesso_remoto = models.CharField(
        max_length=50, null=True, blank=True)
    acesso_id = models.CharField(
        max_length=50, null=True, blank=True)
    acesso_senha = models.CharField(
        max_length=50, null=True, blank=True)
    observacao = models.TextField(
        null=False, blank=True)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.tag_patrimonio

empresa/forms/empresa_forms.py
from django import forms
from ..models import Empresa
from django.forms.utils import ErrorList


class EmpresaForm(forms.ModelForm):
    class Meta:
        model = Empresa
        fields = '__all__'

empresa/views/empresa_views.py
from os import stat
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from ..forms.empresa_forms import EmpresaForm
from ..entidades.empresa import Empresa
from ..services import empresa_service
from equipamento.services import equipamento_service


# Listagem de empresas
def listar_empresas(request):
    empresas = empresa_service.listar_empresas()
    return render(request, 'list_empresa.html', {'empresas': empresas})


# Listando empresa e seus equipamentos
def listar_empresa_id(request, id):
    empresa = empresa_service.listar_empresa_id(id)
    equipamentos = equipamento_service.listar_equipamento_empresa(id)
    return render(request, 'equip_empresa.html', {'empresa': empresa, 'equipamentos': equipamentos})


# erro
def erro_inativar(request):
    return render(request, 'erro_empresa.html')



# Cadastro de empresas
def cadastrar_empresas(request):
    if request.method == "POST":
        form_empresa = EmpresaForm(request.POST)
        if form_empresa.is_valid():
            nome = form_empresa.cleaned_data["nome"]
            cnpj = form_empresa.cleaned_data["cnpj"]
            status = form_empresa.cleaned_data["status"]
            empresa_novo = Empresa(nome=nome, cnpj=cnpj, status=status)
            empresa_service.cadastrar_empresa(empresa_novo)
            return redirect('listar_empresas')
    else:
        form_empresa = EmpresaForm()
    return render(request, 'cad_empresa.html', {'form_empresa': form_empresa})


# Editando empresas
def editar_empresa(request, id):
    empresa_editar = empresa_service.listar_empresa_id(id)
    equipamentos = equipamento_service.listar_equipamento_empresa(id)
    form_empresa = EmpresaForm(request.POST or None, instance=empresa_editar)
    if form_empresa.is_valid():
        nome = form_empresa.cleaned_data["nome"]
        cnpj = form_empresa.cleaned_data["cnpj"]
        status = form_empresa.cleaned_data["status"]
        if status == True:
            empresa_novo = Empresa(nome=nome, cnpj=cnpj, status=status)
            empresa_service.editar_empresa(empresa_editar, empresa_novo)
            return redirect('listar_empresas')
        else:
            if len(equipamentos) == 0 or status == True:
                empresa_novo2 = Empresa(nome=nome, cnpj=cnpj, status=status)
                empresa_service.editar_empresa(empresa_editar, empresa_novo2)
                return redirect('listar_empresas')
            else:
                empresa = empresa_service.listar_empresa_id(id)
                equipamentos = equipamento_service.listar_equipamento_empresa(id)
                return render(request, 'erro_empresa.html', {'empresa': empresa, 'equipamentos': equipamentos})
    return render(request, 'cad_empresa.html', {'form_empresa': form_empresa})

empresa/templates/cad_empresa.html
{% extends 'base.html' %}
{% load meus_filtros %}
{% block title%} Cadastro de Empresa {% endblock title%}

{% block breadcrumb %}
<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="index.html"><i class="bi bi-house-door"></i></a></li>
    <li class="breadcrumb-item active">Empresa</li>
    <li class="breadcrumb-item active">Cadastrar</li>
</ol
{% endblock breadcrumb %}



{% block content %}
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <form method="POST">
                {% csrf_token %}
                <br>
                <div class="form-group">
                    <label>Nome: </label>
                    {{form_empresa.nome.errors}}
                    {{form_empresa.nome|addclass:'form-control'}}
                </div>
                <br>
                <div class="form-group">
                    <label>CNPJ: </label>
                    {{form_empresa.cnpj.errors}}
                    {{form_empresa.cnpj|addclass:'form-control'}}
                </div>
                <br>
                <div class="form-check form-switch" onclick="alterar()">
                    {{form_empresa.status|addclass:'form-check-input'}}
                    <label id="ativoInativo">Ativo</label>
                </div>
                <br>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">
                        <i class="ri-save-2-fill"></i>
                        <span>Salvar</span>
                    </button>
                    <a class="btn btn-secondary" href="{% url 'listar_empresas' %}">
                        <i class="bi bi-box-arrow-right"></i>
                        <span>Voltar</span>
                    </a>
                </div>
                
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block javascript %}
    <script>
        //Aplicando mascara de CNPJ
        $("#id_cnpj").mask("00.000.000/0000-00");


        //Mudando nome para Ativo/Inativo conforme a checkbox
        const button = document.querySelector("#id_status");

        button.addEventListener("click", function() {
            let elemento = document.querySelector('#ativoInativo');
            if (elemento.innerText === 'Ativo') {
                elemento.innerText = 'Inativo';
            } else {
                elemento.innerText = 'Ativo';
            }
        })
    </script>

{% endblock javascript %}

empresa/templates/equip_empresa.html
{% extends 'base.html' %}


{% block title%}
Detalhes Empresa
{% endblock title %}

{% block breadcrumb %}
<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="index.html"><i class="bi bi-house-door"></i></a></li>
    <li class="breadcrumb-item active">Empresa</li>
    <li class="breadcrumb-item active">Detalhes</li>
</o>
{% endblock breadcrumb %}

{% block content %}
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-lg-4">
                <br>
                <div class="box-body box-profile">
                        <h3 class="profile-username text-center">{{empresa.nome}}</h3>
                        <p class="text-muted text-center">{{empresa.cnpj}}</p>
                </div>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>TAG: </th>
                            <th>Tipo: </th>
                            <th>Situação: </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for equipamento in equipamentos %}
                        <tr>
                            <td><a href="#">{{equipamento.tag_patrimonio}}</a></td>
                            <td>{{equipamento.tipo_equipamento}}</td>
                            <td>{{equipamento.get_situacao_display}}<td>
                            <td>
                                {% if equipamento.status == True %}
                                        <div class="form-check form-switch">
                                            <input class="form-check-input" type="checkbox" id="flexSwitchCheckCheckedDisabled" checked="" disabled="">
                                            <label class="form-check-label" for="flexSwitchCheckCheckedDisabled"><b></b></label>
                                        </div>
                                    {% elif equipamento.status == False %}
                                        <div class="form-check form-switch">
                                            <input class="form-check-input" type="checkbox" id="flexSwitchCheckDisabled" disabled="">
                                            <label class="form-check-label" for="flexSwitchCheckDisabled"></label>
                                        </div>
                                    {% endif %}
                            <td>
                        <tr>
                        {% endfor %}
                    </tbody>
                </table>
                    <a href="{% url 'cadastrar_equipamento' %}" class="btn btn-primary btn-block">
                        Cadastrar Equipamento</a>
            </div>
            <div class="col-lg-8">
                <br>
                <div class="nav-tabs-custom">
                    <ul class="nav nav-tabs">
                        <i class="ri-book-mark-fill"></i><li class="active">Histórico</li>
                    </ul>
                    <div class="active tab-pane" id="timeline">
                        </li>
                            {% for equipamento in equipamentos %}
                            <div class="timeline-item">
                                <br>
                                <span class="time"> <i class="ri-calendar-event-line"></i>
                                    {{equipamento.data}}
                                </span>
                                <p class="timeline-header">
                                    Foi cadastrado um(a) {{equipamento.tipo_equipamento}}, {{equipamento.get_situacao_display}} e de tag {{equipamento.tag_patrimonio}}
                                </p>
                                <hr>
                            </div>
                            {% endfor %}
                        </li>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock content %}

empresa/templates/erro_empresa.html
{% extends 'base.html' %} {% block content %}
<div class="row">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-body">
        <br />
        <div
          class="alert alert-danger bg-danger text-light border-0 alert-dismissible fade show"
          role="alert"
        >
          Não foi possível inativar a empresa: "{{empresa.nome}}", pois ela
          possui os seguintes equipamentos cadastrados:
          <button
            type="button"
            class="btn-close btn-close-white"
            data-bs-dismiss="alert"
            aria-label="Close"
          ></button>
        </div>
        <table class="table table-striped">
          <thead>
            <tr>
              <th>TAG:</th>
              <th>Tipo:</th>
              <th>Situação:</th>
              <th scope="col" style="width: 50px">Status:</th>
            </tr>
          </thead>
          <tbody>
            {% for equipamento in equipamentos %}
            <tr>
              <td><a href="#">{{equipamento.tag_patrimonio}}</a></td>
              <td>{{equipamento.tipo_equipamento}}</td>
              <td>{{equipamento.get_situacao_display}}</td>
              <td style="center">
                {% if equipamento.status == True %}
                <div class="form-check form-switch">
                  <input
                    class="form-check-input"
                    type="checkbox"
                    id="flexSwitchCheckCheckedDisabled"
                    checked=""
                    disabled=""
                  />
                  <label
                    class="form-check-label"
                    for="flexSwitchCheckCheckedDisabled"
                    ><b></b
                  ></label>
                </div>
                {% elif equipamento.status == False %}
                <div class="form-check form-switch">
                  <input
                    class="form-check-input"
                    type="checkbox"
                    id="flexSwitchCheckDisabled"
                    disabled=""
                  />
                  <label
                    class="form-check-label"
                    for="flexSwitchCheckDisabled"
                  ></label>
                </div>
                {% endif %}
              </td>

              <td>
                <tr>
                  {% endfor %}
                </tr>
              </td>
            </tr>
          </tbody>
        </table>
        <a class="btn btn-secondary" href="{% url 'listar_empresas' %}">
          <i class="bi bi-box-arrow-right"></i>
          <span>Voltar</span>
        </a>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

empresa/templates/list_empresa.html
{% extends 'base.html' %}


{% block title%}
Listagem de Empresas
{% endblock title %}

{% block breadcrumb %}
<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="index.html"><i class="bi bi-house-door"></i></a></li>
    <li class="breadcrumb-item active">Empresa</li>
    <li class="breadcrumb-item active">Listar</li>
</o>
{% endblock breadcrumb %}



{% block content %}
    <div class="card">
        <div class="card-body">
            <br>
              <!-- Default Tabs -->
              <ul class="nav nav-tabs" id="myTab" role="tablist">
                <li class="nav-item" role="presentation">
                  <button class="nav-link active" id="tab-todos" data-bs-toggle="tab" data-bs-target="#todos" type="button" role="tab" aria-controls="todos" aria-selected="true">Todos</button>
                </li>
                <li class="nav-item" role="presentation">
                  <button class="nav-link" id="tab-ativos" data-bs-toggle="tab" data-bs-target="#ativos" type="button" role="tab" aria-controls="ativos" aria-selected="false">Ativos</button>
                </li>
                <li class="nav-item" role="presentation">
                  <button class="nav-link" id="tab-inativos" data-bs-toggle="tab" data-bs-target="#inativos" type="button" role="tab" aria-controls="inativos" aria-selected="false">Inativos</button>
                </li>
              </ul>
              <div class="tab-content pt-2" id="myTabContent">
                <div class="tab-pane fade active show" id="todos" role="tabpanel" aria-labelledby="tab-todos">
                    <table class="dataTable table table-striped">
                        <br>
                        <thead>
                            <tr>
                                <th scope="col" style="width: 450px">Nome</th>
                                <th scope="col" style="width: 250px">CNPJ</th>
                                <th scope="col" style="width: 50px">Status</th>
                                {% if request.user.tipo != 1 %}
                                <th scope="col" style="width: 50px">Ações</th>
                                {% endif %}
                            </tr>
                        </thead>
                        <tbody>
                            {% for empresa in empresas %}
                            <tr>
                                <th scope="row"><a href="{% url 'listar_empresa_id' empresa.id %}">{{empresa.nome}}</a></th>
                                <th scope="row">{{empresa.cnpj}}</th>
                                <td>
                                    {% if empresa.status == True %}
                                        <div class="form-check form-switch">
                                            <input class="form-check-input" type="checkbox" id="flexSwitchCheckCheckedDisabled" checked="" disabled="">
                                            <label class="form-check-label" for="flexSwitchCheckCheckedDisabled"><b></b></label>
                                        </div>
                                    {% elif empresa.status == False %}
                                        <div class="form-check form-switch">
                                            <input class="form-check-input" type="checkbox" id="flexSwitchCheckDisabled" disabled="">
                                            <label class="form-check-label" for="flexSwitchCheckDisabled"></label>
                                        </div>
                                    {% endif %}
                                </td>
                                {% if request.user.tipo != 1 %}
                                <td style="center">
                                    <a href="{% url 'editar_empresa' empresa.id %}">
                                        <i class="bi bi-pencil-square"></i>
                                    </a>
                                </td>
                                {% endif %}
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="tab-pane fade" id="ativos" role="tabpanel" aria-labelledby="tab-ativos">
                  <table class="dataTable table table-striped">
                        <br>
                        <thead>
                            <tr>
                                <th scope="col" style="width: 450px">Nome</th>
                                <th scope="col" style="width: 250px">CNPJ</th>
                                <th scope="col" style="width: 50px">Status</th>
                                {% if request.user.tipo != 1 %}
                                <th scope="col" style="width: 50px">Ações</th>
                                {% endif %}
                            </tr>
                        </thead>
                        <tbody>
                            {% for empresa in empresas %}
                                {% if empresa.status == True %}
                                    <tr>
                                        <th scope="row">{{empresa.nome}}</th>
                                        <th scope="row">{{empresa.cnpj}}</th>
                                        <td>
                                            <div class="form-check form-switch">
                                            <input class="form-check-input" type="checkbox" id="flexSwitchCheckCheckedDisabled" checked="" disabled="">
                                            <label class="form-check-label" for="flexSwitchCheckCheckedDisabled"><b></b></label>
                                        </div>
                                        </td>
                                        {% if request.user.tipo != 1 %}
                                        <td style="center">
                                            <a href="{% url 'editar_empresa' empresa.id %}">
                                                <i class="bi bi-pencil-square"></i>
                                            </a>
                                        </td>
                                        {% endif %}
                                    </tr>
                                {% endif %}
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="tab-pane fade" id="inativos" role="tabpanel" aria-labelledby="tab-inativos">
                  <table class="dataTable table table-striped">
                        <br>
                        <thead>
                            <tr>
                                <th scope="col" style="width: 450px">Nome</th>
                                <th scope="col" style="width: 250px">CNPJ</th>
                                <th scope="col" style="width: 50px">Status</th>
                                {% if request.user.tipo != 1 %}
                                <th scope="col" style="width: 50px">Ações</th>
                                {% endif %}
                            </tr>
                        </thead>
                        <tbody>
                            {% for empresa in empresas %}
                                {% if empresa.status == False %}
                                    <tr>
                                        <th scope="row">{{empresa.nome}}</th>
                                        <th scope="row">{{empresa.cnpj}}</th>
                                        <td>
                                            <div class="form-check form-switch">
                                                <input class="form-check-input" type="checkbox" id="flexSwitchCheckDisabled" disabled="">
                                                <label class="form-check-label" for="flexSwitchCheckDisabled"></label>
                                            </div>
                                        </td>
                                        {% if request.user.tipo != 1 %}
                                        <td style="center">
                                            <a href="{% url 'editar_empresa' empresa.id %}">
                                                <i class="bi bi-pencil-square"></i>
                                            </a>
                                        </td>
                                        {% endif %}
                                    </tr>
                                {% endif %}
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
              </div><!-- End Default Tabs -->
            </div>
            <br>
            <hr>
            {% if request.user.tipo != 1 %}
            <a href="{% url 'cadastrar_empresa' %}">
                <button class="btn btn-primary">Cadastrar</button>
            </a>
            {% endif %}
            <br>
        </div>
    </div>
{% endblock content %}

{% block javascript %}
    <script>
    $(document).ready(function () {
        $(".dataTable").DataTable({
        language: {
            url: "//cdn.datatables.net/plug-ins/1.12.1/i18n/pt-BR.json",
        },
        });
    });
    </script>

{% endblock javascript %}