app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('dashboard.urls')),
    path('empresa/', include('empresa.urls')),
    path('equipamento/', include('equipamento.urls')),
    path('colaborador/', include('colaborador.urls')),
    path('tipo_equipamento/', include('tipo_equipamento.urls')),
    path('usuario/', include('usuario.urls')),
    path('', include('usuario.urls')),
]

colaborador/urls.py
from django.urls import path
from .views import colaborador_views

urlpatterns = [
    path('cadastrar', colaborador_views.cadastrar_colaboradores,
         name='cadastrar_colaborador'),
    path('listar', colaborador_views.listar_colaboradores,
         name='listar_colaboradores'),
    path('editar/<int:id>', colaborador_views.editar_colaborador,
         name='editar_colaborador'),
]

colaborador/models.py
from django.db import models

# Create your models here.


class Colaborador(models.Model):
    nome = models.CharField(max_length=100, null=False, blank=False)
    cpf = models.CharField(max_length=14, null=False, blank=False, unique=True)
    status = models.BooleanField(default=True)

    class Meta:
        ordering = ['nome']

    def __str__(self):
        return self.nome

colaborador/forms/colaborador_forms.py
from django import forms
from ..models import Colaborador


class ColaboradorForm(forms.ModelForm):
    class Meta:
        model = Colaborador
        fields = '__all__'

colaborador/views/colaborador_views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from ..forms.colaborador_forms import ColaboradorForm
from ..entidades import colaborador
from ..services import colaborador_service


# Listagem de colaboradores
def listar_colaboradores(request):
    colaboradores = colaborador_service.listar_colaboradores()
    return render(request, 'list_colaborador.html', {'colaboradores': colaboradores})


# Cadastro de colaboradores
def cadastrar_colaboradores(request):
    if request.method == "POST":
        form_colaborador = ColaboradorForm(request.POST or None)
        if form_colaborador.is_valid():
            nome = form_colaborador.cleaned_data["nome"]
            cpf = form_colaborador.cleaned_data["cpf"]
            status = form_colaborador.cleaned_data["status"]
            colaborador_novo = colaborador.Colaborador(
                nome=nome, cpf=cpf, status=status)
            colaborador_service.cadastrar_colaborador(colaborador_novo)
            return redirect('listar_colaboradores')
        else:
            print(form_colaborador.errors)
            return render(request, 'cad_colaborador.html', {'form_colaborador': form_colaborador})
    else:
        form_colaborador = ColaboradorForm()
    return render(request, 'cad_colaborador.html', {'form_colaborador': form_colaborador})


# Editando colaboradores
def editar_colaborador(request, id):
    colaborador_editar = colaborador_service.listar_colaborador_id(id)
    form_colaborador = ColaboradorForm(
        request.POST or None, instance=colaborador_editar)
    if form_colaborador.is_valid():
        nome = form_colaborador.cleaned_data["nome"]
        cpf = form_colaborador.cleaned_data["cpf"]
        status = form_colaborador.cleaned_data["status"]
        colaborador_novo = colaborador.Colaborador(nome=nome, cpf=cpf, status=status)
        colaborador_service.editar_colaborador(colaborador_editar, colaborador_novo)
        return redirect('listar_colaboradores')
    return render(request, 'cad_colaborador.html', {'form_colaborador': form_colaborador})

colaborador/templates/cad_colaborador.html
{% extends 'base.html' %}
{% load meus_filtros %}
{% block title%} Cadastro de Colaborador {% endblock title%}

{% block breadcrumb %}
<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="index.html"><i class="bi bi-house-door"></i></a></li>
    <li class="breadcrumb-item active">Colaborador</li>
    <li class="breadcrumb-item active">Cadastrar</li>
</ol
{% endblock breadcrumb %}



{% block content %}
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <form method="POST">
                {% csrf_token %}
                <br>
                <div class="form-group">
                    <label>Nome: </label>
                    {{form_colaborador.nome.errors}}
                    {{form_colaborador.nome|addclass:'form-control'}}
                </div>
                <br>
                <div class="form-group">
                    <label>CPF: </label>
                    {{form_colaborador.cpf.errors}}
                    {{form_colaborador.cpf|addclass:'form-control'}}
                </div>
                <br>
                <div class="form-check form-switch" onclick="alterar()">
                    {{form_colaborador.status|addclass:'form-check-input'}}
                    <label id="ativoInativo">Ativo</label>
                </div>
                <br>
                <hr>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">
                        <i class="ri-save-2-fill"></i>
                        <span>Salvar</span>
                    </button>
                    <a class="btn btn-secondary" href="{% url 'listar_colaboradores' %}">
                        <i class="bi bi-box-arrow-right"></i>
                        <span>Voltar</span>
                    </a>
                </div>
                
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block javascript %}
    <script>
        $("#id_cpf").mask("000.000.000-00");

        const button = document.querySelector("#id_status");

        //Mudando nome para Ativo/Inativo conforme a checkbox
        button.addEventListener("click", function() {
            let elemento = document.querySelector('#ativoInativo');
            if (elemento.innerText === 'Ativo') {
                elemento.innerText = 'Inativo';
            } else {
                elemento.innerText = 'Ativo';
            }
        })
    </script>

{% endblock javascript %}

colaborador/templates/list_colaborador.html
{% extends 'base.html' %}


{% block title%}
Listagem de Colaboradores
{% endblock title %}

{% block breadcrumb %}
<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="index.html"><i class="bi bi-house-door"></i></a></li>
    <li class="breadcrumb-item active">Colaboradores</li>
    <li class="breadcrumb-item active">Listar</li>
</o>
{% endblock breadcrumb %}



{% block content %}
    <div class="card">
        <div class="card-body">
            <br>
              <!-- Default Tabs -->
              <ul class="nav nav-tabs" id="myTab" role="tablist">
                <li class="nav-item" role="presentation">
                  <button class="nav-link active" id="tab-todos" data-bs-toggle="tab" data-bs-target="#todos" type="button" role="tab" aria-controls="todos" aria-selected="true">Todos</button>
                </li>
                <li class="nav-item" role="presentation">
                  <button class="nav-link" id="tab-ativos" data-bs-toggle="tab" data-bs-target="#ativos" type="button" role="tab" aria-controls="ativos" aria-selected="false">Ativos</button>
                </li>
                <li class="nav-item" role="presentation">
                  <button class="nav-link" id="tab-inativos" data-bs-toggle="tab" data-bs-target="#inativos" type="button" role="tab" aria-controls="inativos" aria-selected="false">Inativos</button>
                </li>
              </ul>
              <div class="tab-content pt-2" id="myTabContent">
                <div class="tab-pane fade active show" id="todos" role="tabpanel" aria-labelledby="tab-todos">
                    <table class="dataTable table table-striped">
                        <br>
                        <thead>
                            <tr>
                                <th scope="col" style="width: 450px">Nome</th>
                                <th scope="col" style="width: 250px">CPF</th>
                                <th scope="col" style="width: 50px">Status</th>
                                {% if request.user.tipo != 1 %}
                                <th scope="col" style="width: 50px">Ações</th>
                                {% endif %}
                            </tr>
                        </thead>
                        <tbody>
                            {% for colaborador in colaboradores %}
                            <tr>
                                <th scope="row">{{colaborador.nome}}</th>
                                <th scope="row">{{colaborador.cpf}}</th>
                                <td>
                                    {% if colaborador.status == True %}
                                        <div class="form-check form-switch">
                                            <input class="form-check-input" type="checkbox" id="flexSwitchCheckCheckedDisabled" checked="" disabled="">
                                            <label class="form-check-label" for="flexSwitchCheckCheckedDisabled"><b></b></label>
                                        </div>
                                    {% elif colaborador.status == False %}
                                        <div class="form-check form-switch">
                                            <input class="form-check-input" type="checkbox" id="flexSwitchCheckDisabled" disabled="">
                                            <label class="form-check-label" for="flexSwitchCheckDisabled"></label>
                                        </div>
                                    {% endif %}
                                </td>
                                {% if request.user.tipo != 1 %}
                                <td style="center">
                                    <a href="{% url 'editar_colaborador' colaborador.id %}">
                                        <i class="bi bi-pencil-square"></i>
                                    </a>
                                </td>
                                {% endif %}
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="tab-pane fade" id="ativos" role="tabpanel" aria-labelledby="tab-ativos">
                  <table class="dataTable table table-striped">
                        <br>
                        <thead>
                            <tr>
                                <th scope="col" style="width: 450px">Nome</th>
                                <th scope="col" style="width: 250px">CPF</th>
                                <th scope="col" style="width: 50px">Status</th>
                                {% if request.user.tipo != 1 %}
                                <th scope="col" style="width: 50px">Ações</th>
                                {% endif %}
                            </tr>
                        </thead>
                        <tbody>
                            {% for colaborador in colaboradores %}
                                {% if colaborador.status == True %}
                                    <tr>
                                        <th scope="row">{{colaborador.nome}}</th>
                                        <th scope="row">{{colaborador.cpf}}</th>
                                        <td>
                                            <div class="form-check form-switch">
                                            <input class="form-check-input" type="checkbox" id="flexSwitchCheckCheckedDisabled" checked="" disabled="">
                                            <label class="form-check-label" for="flexSwitchCheckCheckedDisabled"><b></b></label>
                                        </div>
                                        </td>
                                        {% if request.user.tipo != 1 %}
                                        <td style="center">
                                            <a href="{% url 'editar_colaborador' colaborador.id %}">
                                                <i class="bi bi-pencil-square"></i>
                                            </a>
                                        </td>
                                        {% endif %}
                                    </tr>
                                {% endif %}
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="tab-pane fade" id="inativos" role="tabpanel" aria-labelledby="tab-inativos">
                  <table class="dataTable table table-striped">
                        <br>
                        <thead>
                            <tr>
                                <th scope="col" style="width: 450px">Nome</th>
                                <th scope="col" style="width: 250px">CPF</th>
                                <th scope="col" style="width: 50px">Status</th>
                                {% if request.user.tipo != 1 %}
                                    <th scope="col" style="width: 50px">Ações</th>
                                {% endif %}
                            </tr>
                        </thead>
                        <tbody>
                            {% for colaborador in colaboradores %}
                                {% if colaborador.status == False %}
                                    <tr>
                                        <th scope="row">{{colaborador.nome}}</th>
                                        <th scope="row">{{colaborador.cpf}}</th>
                                        <td>
                                            <div class="form-check form-switch">
                                                <input class="form-check-input" type="checkbox" id="flexSwitchCheckDisabled" disabled="">
                                                <label class="form-check-label" for="flexSwitchCheckDisabled"></label>
                                            </div>
                                        </td>
                                        {% if request.user.tipo != 1 %}
                                        <td style="center">
                                            <a href="{% url 'editar_colaborador' colaborador.id %}">
                                                <i class="bi bi-pencil-square"></i>
                                            </a>
                                        </td>
                                        {% endif %}
                                    </tr>
                                {% endif %}
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
              </div><!-- End Default Tabs -->
            </div>
            <br>
            <hr>
            {% if request.user.tipo != 1 %}
            <a href="{% url 'cadastrar_colaborador' %}">
                <button class="btn btn-primary">Cadastrar</button>
            </a>
            {% endif %}
            <br>
        </div>
    </div>
{% endblock content %}

{% block javascript %}
    <script>
    $(document).ready(function () {
        $(".dataTable").DataTable({
        language: {
            url: "//cdn.datatables.net/plug-ins/1.12.1/i18n/pt-BR.json",
        },
        });
    });
    </script>

{% endblock javascript %}